## Multi-stage build for the telemetry collector service.

FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/collector ./cmd/collector

FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=builder /bin/collector /bin/collector

ENV MQ_BASE_URL=http://telemetry-mq:8081

ENTRYPOINT ["/bin/collector"]


