## Multi-stage build for the MQ broker service.

FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/mqbroker ./cmd/mqbroker

FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=builder /bin/mqbroker /bin/mqbroker

ENV LISTEN_ADDR=:8081

ENTRYPOINT ["/bin/mqbroker"]


